CREATE TABLE user_personal_details (
    id VARCHAR(36) PRIMARY KEY,
    user_id VARCHAR(36) NOT NULL UNIQUE,
    salutation VARCHAR(50),
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    date_of_birth DATE,
    gender ENUM('M', 'F'),
    identity_type ENUM('NRIC', 'PASSPORT'),
    identity_number VARCHAR(20) NOT NULL,
    citizenship ENUM('MALAYSIAN', 'FOREIGNER'),
    nationality VARCHAR(100),
    address1 VARCHAR(255),
    address2 VARCHAR(255),
    address3 VARCHAR(255),
    city VARCHAR(100),
    state ENUM('JOHOR', 'KEDAH', 'KELANTAN', 'MALACCA', 'NEGERI_SEMBILAN', 'PAHANG', 'PENANG', 'PERAK', 'PERLIS', 'SABAH', 'SARAWAK', 'SELANGOR', 'TERENGGANU'),
    postcode VARCHAR(10),
    identity_verified BOOLEAN DEFAULT FALSE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES user_signup(id) ON DELETE CASCADE,
    INDEX idx_user_id (user_id),
    INDEX idx_identity_number (identity_number),
    INDEX idx_citizenship (citizenship)
);
